"""Remote server deployment: paths, the generated listener and the deploy script.

Publishing a workspace pushes ``HEAD:main`` to a bare repository hosted on the
deployment server (remote git name ``server``). The server's ``post-receive``
hook — one per workspace, generated by :func:`render_hook` — unpacks the pushed
tree into a checkout, brings the Compose stack up and runs the self-contained
:func:`render_deploy_script` script, which bootstraps the n8n owner, imports the
credentials from ``secrets.json`` and upserts+activates the workflows. Both
generated files are template documents in ``remote/templates/`` carrying the
:data:`GENERATED_MARKER` comment and following the same discipline as the CI
harness templates in ``workspaces/ci.py`` (token substitution, never
f-strings, so braces survive verbatim).
"""

from __future__ import annotations

from ..core.models import ServerConfig
from ..core.templates import read_template
from ..n8n.scopes import REQUIRED_WORKFLOW_SCOPES

GENERATED_MARKER = "n8n-launcher : généré — ne pas modifier à la main."
REMOTE_STATUS_CAPABILITY = "__N8N_LAUNCHER_STATUS_V1__"
# n8n's own execution vocabulary (packages/workflow/src/execution-status.ts).
# ``/rest/executions`` sends no ``finished`` flag, so the launcher only learns
# whether a run is over from its status. The sets mirror upstream exactly:
# ``isTerminalExecutionStatus`` covers the first set, and upstream deliberately
# excludes ``waiting`` and ``unknown`` from it (``unknown`` may still be
# rewritten to ``crashed`` by recovery), which is why they land in the pending
# set instead. The generated script receives both sets through the
# ``__TERMINAL_STATUSES__`` / ``__PENDING_STATUSES__`` tokens so the two parsers
# cannot drift.
TERMINAL_EXECUTION_STATUSES = frozenset({"canceled", "crashed", "error", "success"})
PENDING_EXECUTION_STATUSES = frozenset({"new", "running", "waiting", "unknown"})


def _sh_sq(value: str) -> str:
    """Wrap *value* in single quotes for embedding into bash."""
    return "'" + value.replace("'", "'\\''") + "'"


# ---------------------------------------------------------------------------
# Path / URL helpers
# ---------------------------------------------------------------------------


def resolve_base(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Return the server-side base directory for *cfg*.

    Relative to the ssh user's home; a leading ``~/`` is normalized away so
    both git scp-style URLs and ssh commands agree on the path.
    """
    base = (cfg.base_dir or "").strip()
    if base.startswith("~/"):
        base = base[2:]
    base = base.rstrip("/")
    if base:
        return base
    if workspace_id:
        return f"n8n-launcher/{workspace_id}"
    raise ValueError("base_dir absent : impossible de résoudre le répertoire serveur")


def bare_dir(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Server path of the bare git repository (the ``server`` remote)."""
    return f"{resolve_base(cfg, workspace_id)}.git"


def checkout_dir(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Server path where pushed ``main`` trees are unpacked for compose."""
    return f"{resolve_base(cfg, workspace_id)}/workflow"


def log_path(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Server path of the deployment log."""
    return f"{resolve_base(cfg, workspace_id)}/server.log"


def history_path(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Server path of the bounded JSONL deployment history."""
    return f"{resolve_base(cfg, workspace_id)}/deploy-history.jsonl"


def deploy_script_path(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Server path of the generated deployment/status script."""
    return f"{resolve_base(cfg, workspace_id)}/deploy.py"


def marker_path(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Server path of ``last-deploy.json`` (``{sha,status,error,at}``)."""
    return f"{resolve_base(cfg, workspace_id)}/last-deploy.json"


def server_remote_url(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Git URL (scp syntax) of the workspace's ``server`` remote.

    The scp syntax is the only form that keeps the path relative to the remote
    user's home, where ``base_dir`` lives, and it has no port slot: the port is
    given to ssh itself through ``GIT_SSH_COMMAND`` (see
    :func:`n8n_launcher.git.manager.git_ssh_env`).
    """
    return f"{cfg.user}@{cfg.host}:{bare_dir(cfg, workspace_id)}"


# ---------------------------------------------------------------------------
# Generated post-receive hook
# ---------------------------------------------------------------------------

TEMPLATE_HOOK = read_template("n8n_launcher.remote", "post-receive.sh.tmpl")


def render_hook(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Return the post-receive hook script for *cfg*."""
    content = TEMPLATE_HOOK
    content = content.replace("__MARKER__", GENERATED_MARKER)
    content = content.replace("__BASE__", _sh_sq(resolve_base(cfg, workspace_id)))
    content = content.replace("__BARE__", _sh_sq(bare_dir(cfg, workspace_id)))
    content = content.replace("__WORKFLOW__", _sh_sq(checkout_dir(cfg, workspace_id)))
    content = content.replace("__LOG__", _sh_sq(log_path(cfg, workspace_id)))
    content = content.replace(
        "__PROJECT__", _sh_sq(f"n8n-ws-{workspace_id}" if workspace_id else "")
    )
    content = content.replace("__N8N_PORT__", str(cfg.n8n_port))
    return content


# ---------------------------------------------------------------------------
# Generated deploy.py (runs on the server; stdlib only)
# ---------------------------------------------------------------------------

TEMPLATE_DEPLOY = read_template("n8n_launcher.remote", "deploy.py.tmpl")


def render_deploy_script() -> str:
    """Return the self-contained server deploy script for the workspace tree."""
    content = TEMPLATE_DEPLOY.replace("__MARKER__", GENERATED_MARKER)
    # The status vocabulary is injected as sorted tuples so the generated script
    # carries the exact sets the launcher-side parser uses.
    content = content.replace(
        "__TERMINAL_STATUSES__", _status_set_literal(TERMINAL_EXECUTION_STATUSES)
    )
    content = content.replace(
        "__PENDING_STATUSES__", _status_set_literal(PENDING_EXECUTION_STATUSES)
    )
    # Same reasoning for the API-key scopes: one contract with n8n, shared with
    # the local owner bootstrap.
    content = content.replace("__API_KEY_SCOPES__", _list_literal(REQUIRED_WORKFLOW_SCOPES))
    return content


def _status_set_literal(statuses: frozenset[str]) -> str:
    """Render *statuses* as a Python set literal for the generated script."""
    return "{" + ", ".join(repr(status) for status in sorted(statuses)) + "}"


def _list_literal(values: list[str]) -> str:
    """Render *values* as a Python list literal for the generated script."""
    return "[" + ", ".join(repr(value) for value in values) + "]"


# ---------------------------------------------------------------------------
# Launcher-side helpers
# ---------------------------------------------------------------------------


def build_secrets_document(
    owner_email: str,
    owner_password: str,
    credentials: list[dict],
) -> dict:
    """Assemble the ``secrets.json`` upload payload for a publish."""
    return {
        "owner_email": owner_email,
        "owner_password": owner_password,
        "credentials": credentials,
    }
