"""Remote server deployment: paths, the generated listener and the deploy script.

Publishing a workspace pushes ``HEAD:main`` to a bare repository hosted on the
deployment server (remote git name ``server``). The server's ``post-receive``
hook — one per workspace, generated by :func:`render_hook` — unpacks the pushed
tree into a checkout, brings the Compose stack up and runs the self-contained
:func:`render_deploy_script` script, which bootstraps the n8n owner, imports the
credentials from ``secrets.json`` and upserts+activates the workflows. Both
generated files carry the :data:`GENERATED_MARKER` comment and follow the same
discipline as the CI harness templates in ``workspaces/ci.py`` (plain strings,
never f-strings, so braces survive verbatim).
"""

from __future__ import annotations

from ..core.models import ServerConfig

GENERATED_MARKER = "n8n-launcher : généré — ne pas modifier à la main."


def _sh_sq(value: str) -> str:
    """Wrap *value* in single quotes for embedding into bash."""
    return "'" + value.replace("'", "'\\''") + "'"


# ---------------------------------------------------------------------------
# Path / URL helpers
# ---------------------------------------------------------------------------


def resolve_base(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Return the server-side base directory for *cfg*.

    Relative to the ssh user's home; a leading ``~/`` is normalized away so
    both git scp-style URLs and ssh commands agree on the path.
    """
    base = (cfg.base_dir or "").strip()
    if base.startswith("~/"):
        base = base[2:]
    base = base.rstrip("/")
    if base:
        return base
    if workspace_id:
        return f"n8n-launcher/{workspace_id}"
    raise ValueError("base_dir absent : impossible de résoudre le répertoire serveur")


def bare_dir(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Server path of the bare git repository (the ``server`` remote)."""
    return f"{resolve_base(cfg, workspace_id)}.git"


def checkout_dir(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Server path where pushed ``main`` trees are unpacked for compose."""
    return f"{resolve_base(cfg, workspace_id)}/workflow"


def secrets_path(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Server path of the credentials document (0600, never committed)."""
    return f"{resolve_base(cfg, workspace_id)}/secrets.json"


def log_path(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Server path of the deployment log."""
    return f"{resolve_base(cfg, workspace_id)}/server.log"


def marker_path(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Server path of ``last-deploy.json`` (``{sha,status,error,at}``)."""
    return f"{resolve_base(cfg, workspace_id)}/last-deploy.json"


def server_remote_url(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Git URL (scp syntax) of the workspace's ``server`` remote."""
    return f"{cfg.user}@{cfg.host}:{bare_dir(cfg, workspace_id)}"


# ---------------------------------------------------------------------------
# Generated post-receive hook
# ---------------------------------------------------------------------------

TEMPLATE_HOOK = r"""#!/usr/bin/env bash
# __MARKER__

set -u

BASE=__BASE__
BARE=__BARE__
WORKFLOW=__WORKFLOW__
LOG=__LOG__

marker() {
    python3 - "$1" "$2" "$3" "$BASE" <<'PY'
import json, sys, time
payload = {"sha": sys.argv[1], "status": sys.argv[2], "at": int(time.time())}
if sys.argv[3]:
    payload["error"] = sys.argv[3]
with open(sys.argv[4] + "/last-deploy.json", "w", encoding="utf-8") as fh:
    json.dump(payload, fh)
PY
}

while read -r old new ref; do
    # Only main is deployed; dev pushes go to GitHub/Actions instead.
    [ "$ref" = "refs/heads/main" ] || continue
    # A deleted main produces an all-zeros sha — nothing to deploy.
    [ "$new" != "0000000000000000000000000000000000000000" ] || continue

    mkdir -p "$WORKFLOW"
    if ! git --git-dir="$BARE" archive "$new" | tar -x -C "$WORKFLOW"; then
        marker "$new" "error" "git archive a échoué"
        exit 0
    fi
    if ! (cd "$WORKFLOW" && docker compose up -d) >> "$LOG" 2>&1; then
        marker "$new" "error" "docker compose up -d a échoué"
        exit 0
    fi
    DEPLOY_CHECKOUT="$WORKFLOW" DEPLOY_BASE="$BASE" DEPLOY_N8N_PORT=__N8N_PORT__ \
        python3 "$BASE/deploy.py" "$new" >> "$LOG" 2>&1
done
exit 0
"""


def render_hook(cfg: ServerConfig, workspace_id: str | None = None) -> str:
    """Return the post-receive hook script for *cfg*."""
    content = TEMPLATE_HOOK
    content = content.replace("__MARKER__", GENERATED_MARKER)
    content = content.replace("__BASE__", _sh_sq(resolve_base(cfg, workspace_id)))
    content = content.replace("__BARE__", _sh_sq(bare_dir(cfg, workspace_id)))
    content = content.replace("__WORKFLOW__", _sh_sq(checkout_dir(cfg, workspace_id)))
    content = content.replace("__LOG__", _sh_sq(log_path(cfg, workspace_id)))
    content = content.replace("__N8N_PORT__", str(cfg.n8n_port))
    return content


# ---------------------------------------------------------------------------
# Generated deploy.py (runs on the server; stdlib only)
# ---------------------------------------------------------------------------

TEMPLATE_DEPLOY = r"""#!/usr/bin/env python3
# __MARKER__
#
# Autonomously deploys one n8n workspace: owner bootstrap, credentials import,
# workflow upsert + activation, and SQL migrations. Runs on the server from the
# post-receive hook. Stdlib only.

import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request
from http.cookiejar import CookieJar
from urllib.request import HTTPCookieProcessor, build_opener

CHECKOUT = os.environ.get("DEPLOY_CHECKOUT", ".")
DEPLOY_BASE = os.environ.get("DEPLOY_BASE", ".")
N8N_PORT = int(os.environ.get("DEPLOY_N8N_PORT", "5678"))
ROOT = "http://127.0.0.1:%d" % N8N_PORT
SHA = sys.argv[1] if len(sys.argv) > 1 else "unknown"
SECRETS = os.path.join(DEPLOY_BASE, "secrets.json")
MARKER = os.path.join(DEPLOY_BASE, "last-deploy.json")

WORKFLOW_KEYS = (
    "name",
    "nodes",
    "connections",
    "settings",
    "staticData",
    "pinData",
    "nodeGroups",
    "projectId",
    "parentFolderId",
)


def progress(msg):
    print("[deploy] " + msg, flush=True)


def write_marker(status, error=None):
    payload = {"sha": SHA, "status": status, "at": int(time.time())}
    if error:
        payload["error"] = error
    with open(MARKER, "w", encoding="utf-8") as fh:
        json.dump(payload, fh)


# --- pure helpers (unit-tested via exec) -----------------------------------


def load_secrets(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def collect_workflow_files(checkout):
    # n8nPipelines/*.json + root *.json, mirroring the local import.
    files = []
    for folder in (os.path.join(checkout, "n8nPipelines"), checkout):
        if not os.path.isdir(folder):
            continue
        for name in sorted(os.listdir(folder)):
            entry = os.path.join(folder, name)
            if os.path.isfile(entry) and name.endswith(".json"):
                files.append(entry)
    return files


def create_payload(raw):
    # Whitelist of fields the public create/update schema accepts.
    payload = {}
    for key in WORKFLOW_KEYS:
        if key in raw:
            payload[key] = raw[key]
    payload.setdefault("settings", {})
    return payload


def find_by_name(workflows, name):
    for wf in workflows:
        if wf.get("name") == name:
            return wf
    return None


def rewrite_credential_ids(nodes, id_map):
    # Point node credentials (name,type) -> remote credential id.
    for node in nodes:
        creds = node.get("credentials")
        if not creds:
            continue
        for cred_type, entry in list(creds.items()):
            if not isinstance(entry, dict):
                continue
            key = (entry.get("name"), cred_type)
            if key in id_map:
                entry["id"] = id_map[key]
    return nodes


def migration_files(checkout):
    base = os.path.join(checkout, "db", "migrations")
    if not os.path.isdir(base):
        return []
    return sorted(
        name
        for name in os.listdir(base)
        if name.endswith(".sql") and os.path.isfile(os.path.join(base, name))
    )


# --- HTTP plumbing ----------------------------------------------------------


class Http:
    def __init__(self):
        self.opener = build_opener(HTTPCookieProcessor(CookieJar()))
        self.api_key = ""

    def request(self, method, path, data=None, auth="none", timeout=30.0):
        body = None
        headers = {"Accept": "application/json"}
        if data is not None:
            body = json.dumps(data).encode("utf-8")
            headers["Content-Type"] = "application/json"
        if auth == "key" and self.api_key:
            headers["X-N8N-API-KEY"] = self.api_key
        req = urllib.request.Request(
            ROOT + path, data=body, headers=headers, method=method
        )
        try:
            with self.opener.open(req, timeout=timeout) as resp:
                payload = resp.read()
                return resp.status, json.loads(payload) if payload else {}
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", "replace")
            return exc.code, {"error": detail}
        except Exception as exc:  # connection refused while n8n is starting
            return -1, {"error": str(exc)}


def wait_ready(http, timeout=120.0):
    # Wait until n8n answers on a public endpoint (401 = up but auth needed).
    deadline = time.time() + timeout
    while time.time() < deadline:
        code, _ = http.request("GET", "/api/v1/workflows", auth="key")
        if code in (200, 401, 403):
            return
        time.sleep(2)
    raise RuntimeError("n8n ne répond pas après %ds" % int(timeout))


def ensure_owner(http, email, password):
    # idempotent: owner/setup 400s once an owner exists.
    http.request(
        "POST",
        "/rest/owner/setup",
        {"firstName": "n8n-launcher", "lastName": "deploy", "email": email, "password": password},
        auth="session",
    )
    code, _ = http.request(
        "POST",
        "/rest/login",
        {"emailOrLdapLoginId": email, "password": password},
        auth="session",
    )
    if code >= 400:
        raise RuntimeError("échec de connexion owner")


def ensure_api_key(http):
    code, body = http.request("GET", "/rest/api-keys", auth="session")
    if code >= 400:
        raise RuntimeError("GET /rest/api-keys a échoué: %s" % body)
    for entry in body.get("data", []):
        if entry.get("label") == "n8n-launcher":
            http.request("DELETE", "/rest/api-keys/%s" % entry.get("id"), auth="session")
    code, body = http.request(
        "POST",
        "/rest/api-keys",
        {
            "label": "n8n-launcher",
            "scopes": [
                "workflow:read",
                "workflow:create",
                "workflow:update",
                "workflow:activate",
                "workflow:deactivate",
                "credential:read",
                "credential:create",
                "credential:update",
                "user:read",
                "project:read",
            ],
            "expiresAt": 0,
        },
        auth="session",
    )
    if code >= 400 or not body.get("data", {}).get("apiKey"):
        raise RuntimeError("création d'API key a échoué: %s" % body)
    http.api_key = body["data"]["apiKey"]


def sync_credentials(http, secrets):
    # Create or update remote credentials, returning {(name,type): id}.
    id_map = {}
    code, body = http.request("GET", "/api/v1/credentials?limit=250", auth="key")
    remote = body.get("data", []) if code == 200 else []
    for secret in secrets.get("credentials", []):
        name, ctype = secret["name"], secret["type"]
        existing = None
        for item in remote:
            if item.get("name") == name and item.get("type") == ctype:
                existing = item
                break
        payload = {"name": name, "type": ctype, "data": secret.get("data", {})}
        if existing:
            code, body = http.request(
                "PUT", "/api/v1/credentials/%s" % existing["id"], payload, auth="key"
            )
        else:
            code, body = http.request("POST", "/api/v1/credentials", payload, auth="key")
        if code >= 400:
            raise RuntimeError("credentials %s/%s: %s" % (name, ctype, body.get("error")))
        new_id = body.get("data", {}).get("id")
        id_map[(name, ctype)] = new_id
        progress("credential %s/%s en place" % (name, ctype))
    return id_map


def sync_workflows(http, id_map):
    code, body = http.request("GET", "/api/v1/workflows?limit=250", auth="key")
    remote = body.get("data", []) if code == 200 else []
    for path in collect_workflow_files(CHECKOUT):
        with open(path, encoding="utf-8") as fh:
            raw = json.load(fh)
        if not isinstance(raw, dict) or "nodes" not in raw:
            progress("ignoré (pas un export de workflow): %s" % os.path.basename(path))
            continue
        payload = create_payload(raw)
        payload["nodes"] = rewrite_credential_ids(payload.get("nodes") or [], id_map)
        name = payload["name"]
        existing = find_by_name(remote, name)
        if existing:
            code, body = http.request(
                "PUT", "/api/v1/workflows/%s" % existing["id"], payload, auth="key"
            )
        else:
            code, body = http.request("POST", "/api/v1/workflows", payload, auth="key")
        if code >= 400:
            raise RuntimeError("workflow %s: %s" % (name, body.get("error")))
        new_id = body.get("data", {}).get("id")
        code, _ = http.request("POST", "/api/v1/workflows/%s/activate" % new_id, auth="key")
        if code >= 400:
            raise RuntimeError("activation du workflow %s a échoué" % name)
        progress("workflow %s actif" % name)


def run_migrations():
    migrations = migration_files(CHECKOUT)
    if not migrations:
        return
    services = subprocess.run(
        ["docker", "compose", "config", "--services"],
        capture_output=True,
        text=True,
        cwd=CHECKOUT,
    ).stdout.split()
    if "postgres" not in services:
        progress("db/migrations présentes mais pas de service postgres — ignorées")
        return
    for name in migrations:
        path = os.path.join(CHECKOUT, "db", "migrations", name)
        with open(path, encoding="utf-8") as fh:
            sql = fh.read()
        result = subprocess.run(
            [
                "docker",
                "compose",
                "exec",
                "-T",
                "postgres",
                "psql",
                "-U",
                "n8n",
                "-d",
                "n8n",
                "--set",
                "ON_ERROR_STOP=1",
            ],
            input=sql,
            capture_output=True,
            text=True,
            cwd=CHECKOUT,
        )
        if result.returncode != 0:
            raise RuntimeError(
                "migration %s: %s" % (name, result.stderr.strip() or result.stdout.strip())
            )
        progress("migration %s appliquée" % name)


def main():
    progress("déploiement de %s" % SHA)
    try:
        secrets = load_secrets(SECRETS)
    except Exception as exc:
        write_marker("error", "secrets.json illisible: %s" % exc)
        raise
    http = Http()
    wait_ready(http)
    ensure_owner(http, secrets["owner_email"], secrets["owner_password"])
    ensure_api_key(http)
    id_map = sync_credentials(http, secrets)
    sync_workflows(http, id_map)
    run_migrations()
    write_marker("ok")
    progress("déploiement terminé")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        write_marker("error", str(exc))
        raise
"""


def render_deploy_script() -> str:
    """Return the self-contained server deploy script for the workspace tree."""
    return TEMPLATE_DEPLOY.replace("__MARKER__", GENERATED_MARKER)


# ---------------------------------------------------------------------------
# Launcher-side helpers
# ---------------------------------------------------------------------------


def build_secrets_document(
    owner_email: str,
    owner_password: str,
    credentials: list[dict],
) -> dict:
    """Assemble the ``secrets.json`` upload payload for a publish."""
    return {
        "owner_email": owner_email,
        "owner_password": owner_password,
        "credentials": credentials,
    }
