"""Guards for the PyInstaller hidden-import list generated by ``scripts/build.py``.

The list is derived by walking ``src/n8n_launcher`` rather than hand-kept, so
these tests fail the moment a module is added without the build seeing it — the
drift that made ``n8n.exports`` and ``gui.browser`` invisible to the bundle.
"""

import importlib.util
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
BUILD_SCRIPT = REPO_ROOT / "scripts" / "build.py"
SOURCE_ROOT = REPO_ROOT / "src"


def _load_build():
    """Import ``scripts/build.py`` by path (it is not an installed module)."""
    spec = importlib.util.spec_from_file_location("n8n_build_script", BUILD_SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _modules_on_disk() -> set[str]:
    """Every dotted module name under ``src/n8n_launcher``, mirrors the build walk."""
    modules: set[str] = set()
    for path in (SOURCE_ROOT / "n8n_launcher").rglob("*.py"):
        rel = path.relative_to(SOURCE_ROOT).with_suffix("")
        if rel.name == "__init__":
            rel = rel.parent
        modules.add(".".join(rel.parts))
    return modules


def test_hidden_imports_covers_every_module_on_disk():
    build = _load_build()
    assert _modules_on_disk() <= set(build.HIDDEN_IMPORTS)


def test_hidden_imports_includes_modules_a_literal_list_missed():
    build = _load_build()
    regressed = {
        "n8n_launcher",
        "n8n_launcher.core.templates",
        "n8n_launcher.gui.board",
        "n8n_launcher.gui.browser",
        "n8n_launcher.gui_utils.responsive",
        "n8n_launcher.monitoring.events",
        "n8n_launcher.n8n.exports",
        "n8n_launcher.n8n.scopes",
    }
    assert regressed <= set(build.HIDDEN_IMPORTS)


def test_hidden_imports_has_no_duplicates():
    build = _load_build()
    assert len(build.HIDDEN_IMPORTS) == len(set(build.HIDDEN_IMPORTS))


def test_hidden_imports_package_modules_are_sorted():
    build = _load_build()
    package_modules = [m for m in build.HIDDEN_IMPORTS if m.startswith("n8n_launcher")]
    assert package_modules == sorted(package_modules)


def test_third_party_hidden_is_a_suffix_of_hidden_imports():
    build = _load_build()
    count = len(build.THIRD_PARTY_HIDDEN)
    assert build.HIDDEN_IMPORTS[-count:] == build.THIRD_PARTY_HIDDEN
    assert all(not m.startswith("n8n_launcher") for m in build.THIRD_PARTY_HIDDEN)
